export const odds = [
  {
    homeTeam: 'Manchester City',
    homeOddsFrac: '3/5',
    homeOddsDec: 1.6,
    homePerc: 59,
    homeTeamImage: 'images/Man-City.png',
    draw: 'Draw',
    drawOddsFrac: '17/5',
    drawOddsDec: 4.4,
    drawPerc: 21,
    awayTeam: 'Liverpool',
    awayOddsFrac: '18/5',
    awayOddsDec: 4.6,
    awayPerc: 20,
    awayTeamImage: 'images/Liverpool.png',
  },
  {
    homeTeam: 'Leicester City',
    homeOddsFrac: '5/2',
    homeOddsDec: 3.5,
    homePerc: 27,
    homeTeamImage: 'images/Leicester.png',
    draw: 'Draw',
    drawOddsFrac: '23/10',
    drawOddsDec: 3.3,
    drawPerc: 28,
    awayTeam: 'Crystal Palace',
    awayOddsFrac: '11/10',
    awayOddsDec: 2.1,
    awayPerc: 45,
    awayTeamImage: 'images/Palace.png',
  },
  {
    homeTeam: 'Nottingham Forest',
    homeOddsFrac: '2/1',
    homeOddsDec: 3.0,
    homePerc: 29,
    homeTeamImage: 'images/Nottingham-Forest.png',
    draw: 'Draw',
    drawOddsFrac: '8/5',
    drawOddsDec: 2.6,
    drawPerc: 33,
    awayTeam: 'Brighton',
    awayOddsFrac: '6/5',
    awayOddsDec: 2.2,
    awayPerc: 39,
    awayTeamImage: 'images/Brighton.png',
  },
  {
    homeTeam: 'Ipswich',
    homeOddsFrac: '5/2',
    homeOddsDec: 3.5,
    homePerc: 26,
    homeTeamImage: 'images/Ipswich.png',
    draw: 'Draw',
    drawOddsFrac: '5/2',
    drawOddsDec: 3.5,
    drawPerc: 26,
    awayTeam: 'West Ham United',
    awayOddsFrac: '19/20',
    awayOddsDec: 1.95,
    awayPerc: 47,
    awayTeamImage: 'images/WHU.png',
  },
  {
    homeTeam: 'Newcastle United',
    homeOddsFrac: '7/5',
    homeOddsDec: 2.4,
    homePerc: 39,
    homeTeamImage: 'images/Newcastle.png',
    draw: 'Draw',
    drawOddsFrac: '12/5',
    drawOddsDec: 3.4,
    drawPerc: 27,
    awayTeam: 'Chelsea',
    awayOddsFrac: '17/10',
    awayOddsDec: 2.7,
    awayPerc: 34,
    awayTeamImage: 'images/Chelsea.png',
  },
  {
    homeTeam: 'Southampton',
    homeOddsFrac: '23/10',
    homeOddsDec: 3.3,
    homePerc: 28,
    homeTeamImage: 'images/Southampton.png',
    draw: 'Draw',
    drawOddsFrac: '12/5',
    drawOddsDec: 3.4,
    drawPerc: 28,
    awayTeam: 'Bournemouth',
    awayOddsFrac: '23/20',
    awayOddsDec: 2.15,
    awayPerc: 44,
    awayTeamImage: 'images/Bournemouth.png',
  },
  {
    homeTeam: 'Brentford',
    homeOddsFrac: '33/10',
    homeOddsDec: 4.3,
    homePerc: 22,
    homeTeamImage: 'images/Brentford.png',
    draw: 'Draw',
    drawOddsFrac: '27/10',
    drawOddsDec: 3.7,
    drawPerc: 25,
    awayTeam: 'Arsenal',
    awayOddsFrac: '3/4',
    awayOddsDec: 1.75,
    awayPerc: 53,
    awayTeamImage: 'images/Arsenal.png',
  },
  {
    homeTeam: 'Tottenham',
    homeOddsFrac: '5/4',
    homeOddsDec: 2.25,
    homePerc: 42,
    homeTeamImage: 'images/Tottenham.png',
    draw: 'Draw',
    drawOddsFrac: '29/10',
    drawOddsDec: 3.9,
    drawPerc: 24,
    awayTeam: 'Aston Villa',
    awayOddsFrac: '7/4',
    awayOddsDec: 2.75,
    awayPerc: 34,
    awayTeamImage: 'images/Villa.png',
  },
  {
    homeTeam: 'Everton',
    homeOddsFrac: '7/4',
    homeOddsDec: 2.75,
    homePerc: 34,
    homeTeamImage: 'images/Everton.png',
    draw: 'Draw',
    drawOddsFrac: '12/5',
    drawOddsDec: 3.4,
    drawPerc: 27,
    awayTeam: 'Manchester Utd',
    awayOddsFrac: '7/5',
    awayOddsDec: 2.4,
    awayPerc: 39,
    awayTeamImage: 'images/Man-Utd.png',
  },
  {
    homeTeam: 'Fulham',
    homeOddsFrac: '5/4',
    homeOddsDec: 2.25,
    homePerc: 42,
    homeTeamImage: 'images/Fulham.png',
    draw: 'Draw',
    drawOddsFrac: '23/10',
    drawOddsDec: 3.3,
    drawPerc: 29,
    awayTeam: 'Wolves',
    awayOddsFrac: '11/5',
    awayOddsDec: 3.2,
    awayPerc: 29,
    awayTeamImage: 'images/Wolves.png',
  },
];

export const homeWin = [
  '1-0',
  '2-0',
  '3-0',
  '4-0',
  '5-0',
  '5-1',
  '5-2',
  '5-3',
  '5-4',
  '4-1',
  '4-2',
  '4-3',
  '3-2',
  '3-1',
  '2-1',
];
export const draw = ['0-0', '1-1', '2-2', '3-3', '4-4'];
export const awayWin = [
  '0-1',
  '0-2',
  '0-3',
  '0-4',
  '0-5',
  '1-5',
  '2-5',
  '3-5',
  '4-5',
  '1-4',
  '2-4',
  '3-4',
  '2-3',
  '1-3',
  '1-2',
];
